apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferrotune
  namespace: default
spec:
  selector:
    matchLabels:
      app: ferrotune
  template:
    metadata:
      labels:
        app: ferrotune
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      volumes:
        - name: ferrotune-music
          persistentVolumeClaim:
            claimName: pvc-ferrotune-music
        - name: ferrotune-data
          persistentVolumeClaim:
            claimName: ferrotune-data
      containers:
        - name: ferrotune
          image: ghcr.io/fruitiex/ferrotune:main@sha256:83d1f9680c2e839dfeebf92b136b085fccf19a64cb468ff9296be75b502fe3ad
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: PORT
              value: "4040"
            - name: FERROTUNE_PORT
              value: "4040"
            - name: FERROTUNE_DB_MAX_CONNECTIONS
              value: "1"
            - name: FERROTUNE_DB_JOURNAL_MODE
              value: "delete"
            - name: FERROTUNE_DB_SYNCHRONOUS
              value: "normal"
            - name: FERROTUNE_DB_LOCKING_MODE
              value: "exclusive"
            - name: FERROTUNE_DB_BUSY_TIMEOUT
              value: "1"
          volumeMounts:
            - mountPath: /music
              name: ferrotune-music
            - mountPath: /data
              name: ferrotune-data
