apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferrotune
  namespace: default
spec:
  selector:
    matchLabels:
      app: ferrotune
  template:
    metadata:
      labels:
        app: ferrotune
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      volumes:
        - name: ferrotune-music
          persistentVolumeClaim:
            claimName: pvc-ferrotune-music
        - name: ferrotune-data
          persistentVolumeClaim:
            claimName: ferrotune-data
      containers:
        - name: ferrotune
          image: ghcr.io/fruitiex/ferrotune:main@sha256:a6db8ca94c838ce202682c594826f79a840fbc65b1d0a249e277ceae80dee7a8
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: PORT
              value: "4040"
            - name: FERROTUNE_PORT
              value: "4040"
          volumeMounts:
            - mountPath: /music
              name: ferrotune-music
              readOnly: true
            - mountPath: /data
              name: ferrotune-data
