apiVersion: v1
kind: Service
metadata:
  name: ferrotune-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ferrotune
  ports:
    - name: http
      protocol: TCP
      port: 4040
      targetPort: 4040
